#!/usr/bin/env python3
# Convert PNG textures to row-major RGB565 binary files for .incbin in assembly.
#
# Output byte order is little-endian (RISC-V native halfword order): lhu from a
# converted texture yields the native RGB565 value, matching how .hword color
# constants and rainbow_colors work in this codebase.  fill_rect byte-swaps
# before writing to the framebuffer, so a texture pixel can be passed directly
# to fill_rect as a4.
#
# Usage: png2rgb565.py [assets_dir] [output_dir]

import struct
import sys
from pathlib import Path
from PIL import Image


def convert_png(png_path, out_path):
        img = Image.open(png_path).convert("RGB")
        w, h = img.size
        raw = img.tobytes()
        data = bytearray(w * h * 2)
        for i in range(w * h):
            r = raw[i * 3]
            g = raw[i * 3 + 1]
            b = raw[i * 3 + 2]
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            struct.pack_into("<H", data, i * 2, rgb565)
        out_path.write_bytes(data)
        return w, h, len(data)


def main():
    assets_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("assets")
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("build/assets")
    out_dir.mkdir(parents=True, exist_ok=True)

    pngs = sorted(assets_dir.glob("*.png"))
    if not pngs:
        print(f"No PNG files found in {assets_dir}", file=sys.stderr)
        sys.exit(1)

    header = [
        "# Generated by mise run assets -- do not edit.",
        "# Each .bin is row-major RGB565, little-endian (RISC-V native halfword order).",
        "# Include with:  .incbin \"<name>.bin\"   (add -I build/assets to asm_flags)",
        "",
    ]

    for png in pngs:
        name = png.stem
        out_bin = out_dir / f"{name}.bin"
        w, h, size = convert_png(png, out_bin)
        print(f"  {name}: {w}x{h} -> {out_bin} ({size} bytes)")
        upper = name.upper()
        header.extend([
            f".equ ASSET_{upper}_WIDTH, {w}",
            f".equ ASSET_{upper}_HEIGHT, {h}",
            f".equ ASSET_{upper}_PIXELS, {w * h}",
            f".equ ASSET_{upper}_BYTES, {size}",
            "",
        ])

    header_path = out_dir / "assets.h"
    header_path.write_text("\n".join(header) + "\n")
    print(f"  header: {header_path}")


if __name__ == "__main__":
    main()
